version: '3.2'

services:
  portainer:
    image: portainer/portainer
    hostname: portainer
    networks:
      - proxy
      - portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /server/sisgeo/data/portainer:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

networks:
  portainer: 
    external: false
  proxy:
    external: true
